import { Warehouse, ProductCategory, Product, Receipt, DeliveryOrder, InternalTransfer, InventoryAdjustment, MoveHistoryItem, User } from '../types/inventory';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-1',
    name: 'Elena Vance',
    email: 'elena.vance@stocksense.io',
    role: 'inventory_manager',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    assignedWarehouseId: 'wh-1',
  },
  {
    id: 'usr-2',
    name: 'Marcus Chen',
    email: 'marcus.chen@stocksense.io',
    role: 'warehouse_staff',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    assignedWarehouseId: 'wh-1',
  },
];

export const INITIAL_WAREHOUSES: Warehouse[] = [
  {
    id: 'wh-1',
    code: 'WH-MAIN',
    name: 'Main Warehouse',
    address: '450 Logistics Blvd, Dock 1-4, Chicago, IL',
    type: 'main',
    locations: [
      { id: 'loc-ms', warehouseId: 'wh-1', code: 'LOC-MS', name: 'Main Store', zone: 'Zone A' },
      { id: 'loc-rb', warehouseId: 'wh-1', code: 'LOC-RB', name: 'Receiving Bay', zone: 'Dock 1' },
      { id: 'loc-bs', warehouseId: 'wh-1', code: 'LOC-BS', name: 'Bulk Staging', zone: 'Zone B' },
    ],
  },
  {
    id: 'wh-2',
    code: 'WH-PROD',
    name: 'Production Facility',
    address: '452 Logistics Blvd, Building B, Chicago, IL',
    type: 'production',
    locations: [
      { id: 'loc-pr', warehouseId: 'wh-2', code: 'LOC-PR', name: 'Production Rack', zone: 'Floor 1' },
      { id: 'loc-ab', warehouseId: 'wh-2', code: 'LOC-AB', name: 'Assembly Bay 1', zone: 'Floor 2' },
    ],
  },
  {
    id: 'wh-3',
    code: 'WH-DIST',
    name: 'Regional Distribution Center',
    address: '1200 Intermodal Way, Joliet, IL',
    type: 'distribution',
    locations: [
      { id: 'loc-ra', warehouseId: 'wh-3', code: 'LOC-RA', name: 'Rack A', zone: 'Aisle 3' },
      { id: 'loc-rb2', warehouseId: 'wh-3', code: 'LOC-RB2', name: 'Rack B', zone: 'Aisle 4' },
      { id: 'loc-dz', warehouseId: 'wh-3', code: 'LOC-DZ', name: 'Dispatch Zone', zone: 'Dock 8' },
    ],
  },
];

export const INITIAL_CATEGORIES: ProductCategory[] = [
  { id: 'cat-raw', code: 'RAW', name: 'Raw Materials', description: 'Metals, plastics, and foundational supplies' },
  { id: 'cat-furn', code: 'FURN', name: 'Finished Furniture', description: 'Chairs, desks, workstations' },
  { id: 'cat-elec', code: 'ELEC', name: 'Electronic Components', description: 'Controllers, sensors, power modules' },
  { id: 'cat-pkg', code: 'PKG', name: 'Packaging & Shipping', description: 'Corrugated cartons, strapping, pallets' },
  { id: 'cat-hard', code: 'HARD', name: 'Hardware & Fasteners', description: 'Bolts, nuts, brackets, hinges' },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-steel',
    sku: 'RAW-STL-001',
    name: 'Steel Rods (High Tensile)',
    description: '12mm diameter cold-drawn structural steel rods',
    categoryId: 'cat-raw',
    uom: 'kg',
    costPrice: 4.50,
    sellingPrice: 8.20,
    minStock: 50,
    maxStock: 300,
    reorderQty: 100,
    stockByLocation: {
      'loc-ms': 55,
      'loc-pr': 27,
      'loc-ra': 15,
    },
    createdAt: '2026-08-10T09:00:00Z',
  },
  {
    id: 'prod-chair',
    sku: 'FURN-CHR-002',
    name: 'Ergonomic Task Chair - Mesh',
    description: 'Adjustable lumbar support 5-wheel office chair',
    categoryId: 'cat-furn',
    uom: 'units',
    costPrice: 85.00,
    sellingPrice: 189.00,
    minStock: 20,
    maxStock: 80,
    reorderQty: 25,
    stockByLocation: {
      'loc-ms': 14, // below min stock (alert)
      'loc-ra': 4,
    },
    createdAt: '2026-08-12T10:30:00Z',
  },
  {
    id: 'prod-desk',
    sku: 'FURN-DSK-003',
    name: 'Electric Standing Desk Frame',
    description: 'Dual-motor dual-stage motorized desk frame (Black)',
    categoryId: 'cat-furn',
    uom: 'units',
    costPrice: 140.00,
    sellingPrice: 299.00,
    minStock: 10,
    maxStock: 50,
    reorderQty: 15,
    stockByLocation: {
      'loc-ms': 18,
      'loc-pr': 5,
      'loc-ra': 8,
    },
    createdAt: '2026-08-14T11:15:00Z',
  },
  {
    id: 'prod-ctrl',
    sku: 'ELEC-CTR-004',
    name: 'Micro-Controller PCB v3',
    description: 'Embedded motor control logic board with BLE',
    categoryId: 'cat-elec',
    uom: 'units',
    costPrice: 12.50,
    sellingPrice: 28.00,
    minStock: 40,
    maxStock: 250,
    reorderQty: 80,
    stockByLocation: {
      'loc-ms': 120,
      'loc-pr': 65,
    },
    createdAt: '2026-08-20T08:00:00Z',
  },
  {
    id: 'prod-bolt',
    sku: 'HARD-M8-005',
    name: 'M8 Stainless Flange Bolts',
    description: 'High durability zinc-coated metric hex bolts',
    categoryId: 'cat-hard',
    uom: 'boxes',
    costPrice: 18.00,
    sellingPrice: 32.50,
    minStock: 15,
    maxStock: 100,
    reorderQty: 30,
    stockByLocation: {
      'loc-ms': 42,
      'loc-pr': 18,
      'loc-rb2': 10,
    },
    createdAt: '2026-08-22T14:20:00Z',
  },
  {
    id: 'prod-box',
    sku: 'PKG-BOX-006',
    name: 'Heavy-Duty Shipping Cartons (XL)',
    description: 'Double-walled corrugated packing carton 60x40x40cm',
    categoryId: 'cat-pkg',
    uom: 'boxes',
    costPrice: 2.10,
    sellingPrice: 4.80,
    minStock: 50,
    maxStock: 500,
    reorderQty: 150,
    stockByLocation: {
      'loc-ms': 8, // critically low
      'loc-dz': 12,
    },
    createdAt: '2026-08-25T16:00:00Z',
  },
];

export const INITIAL_RECEIPTS: Receipt[] = [
  {
    id: 'rec-1',
    documentNumber: 'REC-2026-001',
    supplierName: 'Apex Industrial Metals Co.',
    targetWarehouseId: 'wh-1',
    targetLocationId: 'loc-ms',
    dateCreated: '2026-09-22T08:30:00Z',
    dateReceived: '2026-09-23T11:00:00Z',
    status: 'done',
    lines: [
      {
        productId: 'prod-steel',
        productName: 'Steel Rods (High Tensile)',
        sku: 'RAW-STL-001',
        uom: 'kg',
        orderedQty: 100,
        receivedQty: 100,
        unitCost: 4.50,
      },
    ],
    notes: 'Initial bulk shipment for Q3 manufacturing run. Inspected on dock.',
    validatedBy: 'Elena Vance',
    validatedAt: '2026-09-23T11:15:00Z',
  },
  {
    id: 'rec-2',
    documentNumber: 'REC-2026-002',
    supplierName: 'Global Workspace Ergonomics',
    targetWarehouseId: 'wh-1',
    targetLocationId: 'loc-ms',
    dateCreated: '2026-09-24T14:00:00Z',
    status: 'ready',
    lines: [
      {
        productId: 'prod-chair',
        productName: 'Ergonomic Task Chair - Mesh',
        sku: 'FURN-CHR-002',
        uom: 'units',
        orderedQty: 25,
        receivedQty: 25,
        unitCost: 85.00,
      },
      {
        productId: 'prod-desk',
        productName: 'Electric Standing Desk Frame',
        sku: 'FURN-DSK-003',
        uom: 'units',
        orderedQty: 15,
        receivedQty: 15,
        unitCost: 140.00,
      },
    ],
    notes: 'Truck arrived at Receiving Bay. Awaiting dock clerk sign-off.',
  },
  {
    id: 'rec-3',
    documentNumber: 'REC-2026-003',
    supplierName: 'Midwest Box & Packaging Ltd',
    targetWarehouseId: 'wh-1',
    targetLocationId: 'loc-ms',
    dateCreated: '2026-09-25T10:15:00Z',
    status: 'waiting',
    lines: [
      {
        productId: 'prod-box',
        productName: 'Heavy-Duty Shipping Cartons (XL)',
        sku: 'PKG-BOX-006',
        uom: 'boxes',
        orderedQty: 150,
        receivedQty: 0,
        unitCost: 2.10,
      },
    ],
    notes: 'Urgent replenishment for low carton stock. Expected tomorrow morning.',
  },
];

export const INITIAL_DELIVERIES: DeliveryOrder[] = [
  {
    id: 'del-1',
    documentNumber: 'DEL-2026-001',
    customerName: 'Nexus Tech Enterprises',
    shippingAddress: '100 Silicon Way, Tech Park, Suite 400',
    sourceWarehouseId: 'wh-1',
    sourceLocationId: 'loc-ms',
    dateCreated: '2026-09-23T13:45:00Z',
    dateDelivered: '2026-09-24T15:20:00Z',
    status: 'done',
    lines: [
      {
        productId: 'prod-chair',
        productName: 'Ergonomic Task Chair - Mesh',
        sku: 'FURN-CHR-002',
        uom: 'units',
        orderedQty: 10,
        pickedQty: 10,
        unitPrice: 189.00,
      },
    ],
    trackingNumber: 'FX-884920491',
    notes: 'Priority corporate order for headquarters renovation.',
    validatedBy: 'Marcus Chen',
    validatedAt: '2026-09-24T15:20:00Z',
  },
  {
    id: 'del-2',
    documentNumber: 'DEL-2026-002',
    customerName: 'Vanguard Industrial Systems',
    shippingAddress: '780 Manufacturing Rd, Detroit, MI',
    sourceWarehouseId: 'wh-1',
    sourceLocationId: 'loc-ms',
    dateCreated: '2026-09-25T09:00:00Z',
    status: 'ready',
    lines: [
      {
        productId: 'prod-steel',
        productName: 'Steel Rods (High Tensile)',
        sku: 'RAW-STL-001',
        uom: 'kg',
        orderedQty: 20,
        pickedQty: 20,
        unitPrice: 8.20,
      },
    ],
    trackingNumber: 'UPS-1Z99948201',
    notes: 'Ready at dispatch staging dock. Courier scheduled for 3 PM.',
  },
  {
    id: 'del-3',
    documentNumber: 'DEL-2026-003',
    customerName: 'Apex Co-Working Spaces',
    shippingAddress: '312 Michigan Ave, Chicago, IL',
    sourceWarehouseId: 'wh-1',
    sourceLocationId: 'loc-ms',
    dateCreated: '2026-09-25T11:30:00Z',
    status: 'waiting',
    lines: [
      {
        productId: 'prod-desk',
        productName: 'Electric Standing Desk Frame',
        sku: 'FURN-DSK-003',
        uom: 'units',
        orderedQty: 5,
        pickedQty: 0,
        unitPrice: 299.00,
      },
      {
        productId: 'prod-chair',
        productName: 'Ergonomic Task Chair - Mesh',
        sku: 'FURN-CHR-002',
        uom: 'units',
        orderedQty: 5,
        pickedQty: 0,
        unitPrice: 189.00,
      },
    ],
    notes: 'Awaiting stock confirmation before picking.',
  },
];

export const INITIAL_TRANSFERS: InternalTransfer[] = [
  {
    id: 'trf-1',
    documentNumber: 'TRF-2026-001',
    sourceWarehouseId: 'wh-1',
    sourceLocationId: 'loc-ms',
    destWarehouseId: 'wh-2',
    destLocationId: 'loc-pr',
    dateCreated: '2026-09-24T09:30:00Z',
    status: 'done',
    lines: [
      {
        productId: 'prod-steel',
        productName: 'Steel Rods (High Tensile)',
        sku: 'RAW-STL-001',
        uom: 'kg',
        quantity: 30,
      },
    ],
    reason: 'Replenishing production floor buffer for assembly shift #2',
    performedBy: 'Marcus Chen',
    validatedBy: 'Elena Vance',
    validatedAt: '2026-09-24T10:00:00Z',
  },
  {
    id: 'trf-2',
    documentNumber: 'TRF-2026-002',
    sourceWarehouseId: 'wh-1',
    sourceLocationId: 'loc-ms',
    destWarehouseId: 'wh-3',
    destLocationId: 'loc-ra',
    dateCreated: '2026-09-25T14:10:00Z',
    status: 'ready',
    lines: [
      {
        productId: 'prod-ctrl',
        productName: 'Micro-Controller PCB v3',
        sku: 'ELEC-CTR-004',
        uom: 'units',
        quantity: 25,
      },
    ],
    reason: 'Balancing inventory across Chicago Main and Joliet Distribution Hub',
    performedBy: 'Marcus Chen',
  },
];

export const INITIAL_ADJUSTMENTS: InventoryAdjustment[] = [
  {
    id: 'adj-1',
    documentNumber: 'ADJ-2026-001',
    warehouseId: 'wh-2',
    locationId: 'loc-pr',
    productId: 'prod-steel',
    productName: 'Steel Rods (High Tensile)',
    sku: 'RAW-STL-001',
    uom: 'kg',
    recordedQty: 30,
    countedQty: 27,
    differenceQty: -3,
    reason: 'damaged',
    notes: '3 kg bent rods found during morning inspection; removed to scrap bin.',
    createdBy: 'Marcus Chen',
    createdAt: '2026-09-24T11:45:00Z',
    status: 'done',
  },
];

export const INITIAL_MOVE_HISTORY: MoveHistoryItem[] = [
  {
    id: 'mov-1',
    timestamp: '2026-09-23T11:15:00Z',
    documentType: 'receipt',
    documentNumber: 'REC-2026-001',
    productId: 'prod-steel',
    productName: 'Steel Rods (High Tensile)',
    sku: 'RAW-STL-001',
    uom: 'kg',
    fromLocationName: 'Vendor: Apex Metals',
    toLocationName: 'Main Store (WH-MAIN)',
    quantityChange: 100,
    balanceAfter: 100,
    performedBy: 'Elena Vance',
    notes: 'Received initial PO-4401 in full',
  },
  {
    id: 'mov-2',
    timestamp: '2026-09-24T10:00:00Z',
    documentType: 'transfer',
    documentNumber: 'TRF-2026-001',
    productId: 'prod-steel',
    productName: 'Steel Rods (High Tensile)',
    sku: 'RAW-STL-001',
    uom: 'kg',
    fromLocationName: 'Main Store (WH-MAIN)',
    toLocationName: 'Production Rack (WH-PROD)',
    quantityChange: 30,
    balanceAfter: 70,
    performedBy: 'Marcus Chen',
    notes: 'Internal move for line assembly',
  },
  {
    id: 'mov-3',
    timestamp: '2026-09-24T11:45:00Z',
    documentType: 'adjustment',
    documentNumber: 'ADJ-2026-001',
    productId: 'prod-steel',
    productName: 'Steel Rods (High Tensile)',
    sku: 'RAW-STL-001',
    uom: 'kg',
    fromLocationName: 'Production Rack (WH-PROD)',
    toLocationName: 'Scrap / Loss Bin',
    quantityChange: -3,
    balanceAfter: 27,
    performedBy: 'Marcus Chen',
    notes: '3 kg damaged steel rods written off',
  },
  {
    id: 'mov-4',
    timestamp: '2026-09-24T15:20:00Z',
    documentType: 'delivery',
    documentNumber: 'DEL-2026-001',
    productId: 'prod-chair',
    productName: 'Ergonomic Task Chair - Mesh',
    sku: 'FURN-CHR-002',
    uom: 'units',
    fromLocationName: 'Main Store (WH-MAIN)',
    toLocationName: 'Customer: Nexus Tech',
    quantityChange: -10,
    balanceAfter: 14,
    performedBy: 'Marcus Chen',
    notes: 'Picked, packed, and loaded on courier',
  },
];
